### ISSUE TITLE
Problème d'écriture d'archive sur Windows

### ISSUE THREAD

**Issue by Seph29** [kairoh/studio#1]
**Describe the bug**
Bonjour j'ai un problème de conversion
- FS (2.x) vers éditable  
pas d'erreur en 0.3.1

**To Reproduce**
1. Go to 'STUdio'
2. Click on 'Convertir ce pack d'histoires au format archive (éditable)' 

**Screenshots**
![bug](https://user-images.githubusercontent.com/199496/156926385-9954a6ba-8675-4080-9c0b-4367f364fd86.jpg)

**Desktop and environment (please complete the following information):**
 - OS: WIN11
 - Browser BRAVE
 - Java version: openjdk version "11.0.14" 2022-01-18
 - Maven version: 
 - STUdio application version 0.4.0

**Logs**

[studio-latest - bug1.log](https://github.com/kairoh/studio/files/8192659/studio-latest.-.bug1.log)

**Comment by kairoh** [comment]
Le chemin pour écrire le zip était invalide sur Windows (slash vs antislash ) ...

Pouvez-vous essayer avec cette version : https://github.com/kairoh/studio/suites/5728945335/artifacts/189616930 ?

**Comment by Seph29** [comment]
Bonjour Kairoh
Ca me semble OK pour les archives V2 et V1
