### ISSUE TITLE
Waiting for device partition

### ISSUE THREAD

**Issue by Bidibooum** [kairoh/studio#2]
Hello, I have a problem on MACOS 11.6 (20G165).

When i lanuch the 0.40 no problem, my library load.

but when i plug my device, problem:
On V1 or V2 devices.

![Capture d’écran 2022-03-11 à 18 37 40](https://user-images.githubusercontent.com/65886137/157921479-86125804-1f81-4944-87de-c948fd4e6ab1.png)

**Comment by kairoh** [comment]
Device are filtered by name, it was _/dev/s*_ but MacOS seems to use _/dev/disk*_ .

Please could you test with this version : https://github.com/kairoh/studio/suites/5728945335/artifacts/189616930 ?

**Comment by Bidibooum** [comment]
Hello,

It's ok with this version ;-)

Thanks

**Comment by campafap** [comment]
@kairoh hello ! Thank for the work. But i have the same problem but on Ventura. @Seph29 propose this : https://github.com/kairoh/studio/pull/13/commits/1312a5696a983714160769ed24bcc0fa0e2ea957 #13 but i can't fix it on my own. I need a new release, i can't edit myself sorry
