### ISSUE TITLE
"Stream of unsupported format" with some pack

### ISSUE THREAD

**Issue by kairoh** [kairoh/studio#5]
**Describe the bug**
_Stream of unsupported format_ is thrown with some pack.

**To Reproduce**
Convert pack having some node without audio asset.

**Expected behavior**
Successful conversion using default "blank" MP3.

**Comment by kairoh** [comment]
The embedded blank.mp3 was corrupted when extracted from code constant to a dedicated file.
Fixed by restoring the older value.

**Comment by malexxx** [comment]
Thanks
